# NOTE: update this with your service name
app: swap
service: gateway

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  chidlren:
    handler: handlers/children/index.handler
    events:
      - http:
          path: /nodes/{id}/children
          method: get
          cors: true
      - http:
          path: /nodes/{id}/children
          method: post
          cors: true
  parents:
    handler: handlers/parents/index.handler
    events:
      - http:
          path: /nodes/{id}/parents
          method: get
          cors: true
  node:
    handler: handlers/nodes/index.handler
    events:
      - http:
          path: /nodes
          method: post
          cors: true
      - http:
          path: /nodes/{id}
          method: any
          cors: true
  query:
    handler: handlers/nodes/query/index.handler
    events:
      - http:
          path: /nodes
          method: get
          cors: true
      - http:
          path: /nodes/title/{title}
          method: get
          cors: true

  belongs:
    handler: handlers/relationships/belongs/index.handler
    events:
      - http:
          path: /relationships/belongs/from/{from}/to/{to}
          method: post
          cors: true
      - http:
          path: /relationships/belongs/from/{from}/to/{to}
          method: delete
          cors: true
      - http:
          path: /relationships/belongs/from/{from}
          method: get
          cors: true
      - http:
          path: /relationships/belongs/to/{to}
          method: get
          cors: true
      - http:
          path: /relationships/belongs/from/{from}/to/{to}
          method: get
          cors: true

custom:
  bundle:
    caching: false
    sourcemaps: false
